{{- if .Values.service.obshell.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seekdb.fullname" . }}-obshell
  labels:
    {{- include "seekdb.labels" . | nindent 4 }}
  {{- with .Values.service.obshell.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.obshell.type }}
  ports:
    - port: {{ .Values.service.obshell.port }}
      targetPort: 2886
      protocol: TCP
      name: obshell
      {{- if and (or (eq .Values.service.obshell.type "NodePort") (eq .Values.service.obshell.type "LoadBalancer")) .Values.service.obshell.nodePort }}
      nodePort: {{ .Values.service.obshell.nodePort }}
      {{- end }}
  selector:
    {{- include "seekdb.selectorLabels" . | nindent 4 }}
{{- end }}
