{{- if .Values.service.sql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "seekdb.fullname" . }}-sql
  labels:
    {{- include "seekdb.labels" . | nindent 4 }}
  {{- with .Values.service.sql.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.sql.type }}
  ports:
    - port: {{ .Values.service.sql.port }}
      targetPort: 2881
      protocol: TCP
      name: sql
      {{- if and (or (eq .Values.service.sql.type "NodePort") (eq .Values.service.sql.type "LoadBalancer")) .Values.service.sql.nodePort }}
      nodePort: {{ .Values.service.sql.nodePort }}
      {{- end }}
  selector:
    {{- include "seekdb.selectorLabels" . | nindent 4 }}
{{- end }}
